spring:
  jackson:
    serialization:
      indent-output: true
  jpa: 
    database: MYSQL
    hibernate: 
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: false
        cache.use_query_cache: true
        cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
        net.sf.ehcache.configurationResourceName: ehcache.xml
  
    
service:
  database: test
  upload-dir: /home/java/upload
  c3p0: 
    jdbcUrl: jdbc:mysql://192.168.3.241:3306/${service.database}?characterEncoding=utf-8
    driverClass: com.mysql.jdbc.Driver
    user: root
    password: root
    minPoolSize: 5
    maxPoolSize: 20

debug: 
  false