spring: 
  jackson: 
    serialization: 
      indent-output: true
  servlet:
    multipart:
      location: E:\upload
     
#kafka config
kafka: 
  consumer: 
    group: ${spring.application.name}
    interval: 1000
    offsetReset: smallest
    zookeeper:
      connect: ${service.kafka.zookeeper.connect}
      connectTimeOut: 15000
      sessionTimeout: 15000
      synctime: 200
    topics:
      - name: psgcar_control_result_report
        partitions: 8
        replicationFactor: 1
        
  producer:
    broker:
      connect: ${service.kafka.broker.connect}
    zookeeper:
      connect: ${service.kafka.zookeeper.connect}
      connectTimeOut: 15000
      sessionTimeout: 15000
      synctime: 200
    serializer: kafka.serializer.DefaultEncoder
    acks: 0
    partitioner: com.config.kafka.MessagePartitioner
    partitions: 8
        
debug: 
  false


    