spring:
  jackson:
    serialization:
      indent-output: true
  servlet:
    multipart:
      location: /home/java/upload     
     
      
mybatis:
  mapper-locations:
  - classpath:mapper1/*.xml
  - classpath:mapper2/*.xml
  configuration:
    cache-enabled: true
  
    
service:
  database: test
  upload-dir: /home/java/upload
  c3p0: 
    jdbcUrl: jdbc:mysql://192.168.3.241:3306/${service.database}?characterEncoding=utf-8
    driverClass: com.mysql.jdbc.Driver
    user: root
    password: root
    minPoolSize: 20
    maxPoolSize: 30
    
debug: 
  false